### PR TITLE
Facebook Login Website fixed 

### PR DESCRIPTION
**Pull request by igorsilvaaa34**
Hello,
Here is the facebook website fixed for blackeye, soon I will bring more updates.
[login.txt](https://github.com/j-dogcoder/Blackeye-2.0/files/5577588/login.txt)

I hope you like !

Warns: This code was not translated into English, because I am Portuguese, but you can translate if you want.

### CODE REVIEW

**Comment by j-dogcoder** [comment]
@igorsilvaaa34 Have you seen the way the other files are structured? Just inserting a file in the pull request also will not work. Please create a branch or fork, make the changes necessary, and then create a pull request. Also, this pull request is trying to take the changes in master that I have made and put them into my patch branch. This is not how a pull request works.

**Review by j-dogcoder — CHANGES_REQUESTED** [review]
@igorsilvaaa34 Have you seen the way the other files are structured? Just inserting a file in the pull request also will not work. Please create a branch or fork, make the changes necessary, and then create a pull request. Also, this pull request is trying to take the changes in master that I have made and put them into my patch branch. This is not how a pull request works.

**Comment by j-dogcoder-2ndary** [comment]
Woops!

**Comment by j-dogcoder** [comment]
We have fixed this. This is now a stale request.

**Pull request closed without merging**
